<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.signal import savgol_coeffs
savgol_coeffs(5, 2)

array([-0.08571429,  0.34285714,  0.48571429,  0.34285714, -0.08571429])

In [ ]:
savgol_coeffs(5, 2, deriv=1)

array([ 2.00000000e-01,  1.00000000e-01,  2.07548111e-16, -1.00000000e-01,
       -2.00000000e-01])

Note that use='dot' simply reverses the coefficients.


In [ ]:
savgol_coeffs(5, 2, pos=3)

array([ 0.25714286,  0.37142857,  0.34285714,  0.17142857, -0.14285714])

In [ ]:
savgol_coeffs(5, 2, pos=3, use='dot')

array([-0.14285714,  0.17142857,  0.34285714,  0.37142857,  0.25714286])

In [ ]:
savgol_coeffs(4, 2, pos=3, deriv=1, use='dot')

array([0.45,  -0.85,  -0.65,  1.05])

`x` contains data from the parabola x = t**2, sampled at
t = -1, 0, 1, 2, 3.  `c` holds the coefficients that will compute the
derivative at the last position.  When dotted with `x` the result should
be 6.


In [ ]:
x = np.array([1, 0, 1, 4, 9])
c = savgol_coeffs(5, 2, pos=4, deriv=1, use='dot')
c.dot(x)

6.0