<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np

Davenport angles are a generalization of Euler angles, when we use the
canonical basis axes:


In [ ]:
ex = [1, 0, 0]
ey = [0, 1, 0]
ez = [0, 0, 1]

Represent a single rotation:


In [ ]:
r = R.from_rotvec([0, 0, np.pi/2])
r.as_davenport([ez, ex, ey], 'extrinsic', degrees=True)

array([90.,  0.,  0.])

In [ ]:
r.as_euler('zxy', degrees=True)

array([90.,  0.,  0.])

In [ ]:
r.as_davenport([ez, ex, ey], 'extrinsic', degrees=True).shape

(3,)

Represent a stack of single rotation:


In [ ]:
r = R.from_rotvec([[0, 0, np.pi/2]])
r.as_davenport([ez, ex, ey], 'extrinsic', degrees=True)

array([[90.,  0.,  0.]])

In [ ]:
r.as_davenport([ez, ex, ey], 'extrinsic', degrees=True).shape

(1, 3)

Represent multiple rotations in a single object:


In [ ]:
r = R.from_rotvec([
[0, 0, 90],
[45, 0, 0]], degrees=True)
r.as_davenport([ez, ex, ey], 'extrinsic', degrees=True)

array([[90.,  0.,  0.],
       [ 0., 45.,  0.]])

In [ ]:
r.as_davenport([ez, ex, ey], 'extrinsic', degrees=True).shape

(2, 3)