<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Evaluate the function of order 0 at one point.


In [ ]:
from scipy.special import iv
iv(0, 1.)

1.2660658777520084

Evaluate the function at one point for different orders.


In [ ]:
iv(0, 1.), iv(1, 1.), iv(1.5, 1.)

(1.2660658777520084, 0.565159103992485, 0.2935253263474798)

The evaluation for different orders can be carried out in one call by
providing a list or NumPy array as argument for the `v` parameter:


In [ ]:
iv([0, 1, 1.5], 1.)

array([1.26606588, 0.5651591 , 0.29352533])

Evaluate the function at several points for order 0 by providing an
array for `z`.


In [ ]:
import numpy as np
points = np.array([-2., 0., 3.])
iv(0, points)

array([2.2795853 , 1.        , 4.88079259])

If `z` is an array, the order parameter `v` must be broadcastable to
the correct shape if different orders shall be computed in one call.
To calculate the orders 0 and 1 for an 1D array:


In [ ]:
orders = np.array([[0], [1]])
orders.shape

(2, 1)

In [ ]:
iv(orders, points)

array([[ 2.2795853 ,  1.        ,  4.88079259],
       [-1.59063685,  0.        ,  3.95337022]])

Plot the functions of order 0 to 3 from -5 to 5.


In [ ]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
x = np.linspace(-5., 5., 1000)
for i in range(4):
    ax.plot(x, iv(i, x), label=f'$I_{i!r}$')
ax.legend()
plt.show()