<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.stats import iqr
x = np.array([[10, 7, 4], [3, 2, 1]])
x

array([[10,  7,  4],
       [ 3,  2,  1]])

In [ ]:
iqr(x)

4.0

In [ ]:
iqr(x, axis=0)

array([ 3.5,  2.5,  1.5])

In [ ]:
iqr(x, axis=1)

array([ 3.,  1.])

In [ ]:
iqr(x, axis=1, keepdims=True)

array([[ 3.],
       [ 1.]])