<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
import scipy.special as sc

It is 1 for `x > 0`.


In [ ]:
sc.gammasgn([1, 2, 3, 4])

array([1., 1., 1., 1.])

It alternates between -1 and 1 for negative integers.


In [ ]:
sc.gammasgn([-0.5, -1.5, -2.5, -3.5])

array([-1.,  1., -1.,  1.])

It can be used to compute the gamma function.


In [ ]:
x = [1.5, 0.5, -0.5, -1.5]
sc.gammasgn(x) * np.exp(sc.gammaln(x))

array([ 0.88622693,  1.77245385, -3.5449077 ,  2.3632718 ])

In [ ]:
sc.gamma(x)

array([ 0.88622693,  1.77245385, -3.5449077 ,  2.3632718 ])