<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.stats import directional_stats
data = np.array([[3, 4],    # first observation, 2D vector space
                 [6, -8]])  # second observation
dirstats = directional_stats(data)
dirstats.mean_direction

array([1., 0.])

In contrast, the regular sample mean of the vectors would be influenced
by the magnitude of each observation. Furthermore, the result would not be
a unit vector.


In [ ]:
data.mean(axis=0)

array([4.5, -2.])

An exemplary use case for `directional_stats` is to find a *meaningful*
center for a set of observations on a sphere, e.g. geographical locations.


In [ ]:
data = np.array([[0.8660254, 0.5, 0.],
                 [0.8660254, -0.5, 0.]])
dirstats = directional_stats(data)
dirstats.mean_direction

array([1., 0., 0.])

The regular sample mean on the other hand yields a result which does not
lie on the surface of the sphere.


In [ ]:
data.mean(axis=0)

array([0.8660254, 0., 0.])

The function also returns the mean resultant length, which
can be used to calculate a directional variance. For example, using the
definition ``Var(z) = 1 - R`` from [2] where ``R`` is the
mean resultant length, we can calculate the directional variance of the
vectors in the above example as:


In [ ]:
1 - dirstats.mean_resultant_length

0.13397459716167093