<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np

Initialize a single rotation:


In [ ]:
r = R.from_rotvec(np.pi/2 * np.array([0, 0, 1]))
r.as_rotvec()

array([0.        , 0.        , 1.57079633])

In [ ]:
r.as_rotvec().shape

(3,)

Initialize a rotation in degrees, and view it in degrees:


In [ ]:
r = R.from_rotvec(45 * np.array([0, 1, 0]), degrees=True)
r.as_rotvec(degrees=True)

array([ 0., 45.,  0.])

Initialize multiple rotations in one object:


In [ ]:
r = R.from_rotvec([
[0, 0, np.pi/2],
[np.pi/2, 0, 0]])
r.as_rotvec()

array([[0.        , 0.        , 1.57079633],
       [1.57079633, 0.        , 0.        ]])

In [ ]:
r.as_rotvec().shape

(2, 3)

It is also possible to have a stack of a single rotaton:


In [ ]:
r = R.from_rotvec([[0, 0, np.pi/2]])
r.as_rotvec().shape

(1, 3)