<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
import scipy.special as sc

It has poles when `c` is a negative integer.


In [ ]:
sc.hyp2f1(1, 1, -2, 1)

inf

It is a polynomial when `a` or `b` is a negative integer.


In [ ]:
a, b, c = -1, 1, 1.5
z = np.linspace(0, 1, 5)
sc.hyp2f1(a, b, c, z)

array([1.        , 0.83333333, 0.66666667, 0.5       , 0.33333333])

In [ ]:
1 + a * b * z / c

array([1.        , 0.83333333, 0.66666667, 0.5       , 0.33333333])

It is symmetric in `a` and `b`.


In [ ]:
a = np.linspace(0, 1, 5)
b = np.linspace(0, 1, 5)
sc.hyp2f1(a, b, 1, 0.5)

array([1.        , 1.03997334, 1.1803406 , 1.47074441, 2.        ])

In [ ]:
sc.hyp2f1(b, a, 1, 0.5)

array([1.        , 1.03997334, 1.1803406 , 1.47074441, 2.        ])

It contains many other functions as special cases.


In [ ]:
z = 0.5
sc.hyp2f1(1, 1, 2, z)

1.3862943611198901

In [ ]:
-np.log(1 - z) / z

1.3862943611198906

In [ ]:
sc.hyp2f1(0.5, 1, 1.5, z**2)

1.098612288668109

In [ ]:
np.log((1 + z) / (1 - z)) / (2 * z)

1.0986122886681098

In [ ]:
sc.hyp2f1(0.5, 1, 1.5, -z**2)

0.9272952180016117

In [ ]:
np.arctan(z) / z

0.9272952180016122